config/routes.rb
Rails.application.routes.draw do
 root :to => 'habits#new'

 resources :habits
 
end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :level
  belongs_to :habit 

end

app/models/habit.rb
class Habit < ActiveRecord::Base
  belongs_to :user
  has_many :levels
  has_many :days, through: :levels

  accepts_nested_attributes_for :levels, :days


  def evaluate(user)
    
    levels.each { |level| level.evaluate }
    user.missed_levels << levels.where(passed: false).ids 
    user.missed_days << days.where(missed: true).ids 
    user.save

  end

    
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :habit
  belongs_to :user
  has_many :days

  accepts_nested_attributes_for :days

  def evaluate
    if days.where(missed: true ).count == 3
      update_attributes(passed: false)
    else
      update_attributes(passed: true)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :habits
  has_many :levels
  has_many :days 

  serialize :missed_days, Array
  serialize :missed_levels, Array

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_user
  
  def index
    @habits = Habit.all
  end

  def new
    @habit = @user.habits.new
    @level = @habit.levels.new
    3.times { @level.days.build }
  end

  def create
    @habit = @user.habits.new(habit_params)
    @levels = @habit.levels

    if @habit.save
      @habit.evaluate(@user)
      redirect_to habits_path
    else
      render :new 
    end
  end


  private

  def habit_params
    params.require(:habit).permit(
      :user_id,
      levels_attributes:[
      :passed,
      days_attributes:[
      :missed,:level_id]])
  end

  def set_user
    @user = User.find(1) # use params or whatever
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/index.html.erb
<%@habits.each do |habit| %>
  <%= habit.levels.count %> <br/> 
  <%= User.find(1).missed_days %>
<%end%>
<br/>
<%=link_to "NEW", new_habit_path %>

app/views/habits/new.html.erb
<%= form_for @habit do |habit| %>
  <% 5.times.each_with_index do |number, index| %>
    <h1>Level <%= index + 1 %></h1>
    <%= habit.fields_for :levels do |level| %>
      <%= level.fields_for :days do |day| %>
        <%= day.label :missed %>
        <%= day.check_box :missed %> <br/>
      <% end %>
    <% end %>
  <% end %>
  <%= habit.submit "submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>So</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>